### ISSUE TITLE
有没有photos版本的

### ISSUE THREAD

**Issue by dengdaiderizi521** [luowenxing/MTImagePicker#1]
AssetsLibrary在IOS9之后被弃用，是否有Photos版本的？

**Comment by luowenxing** [comment]
暂时还没有！之后有时间的话会更新一个，ios8以上集成photo。

**Comment by dengdaiderizi521** [comment]
@luowenxing 期待着photos版本的早日到来。

**Comment by luowenxing** [comment]
photos版本已更新

**Comment by dengdaiderizi521** [comment]
@luowenxing 非常感谢！如果有BUG，我会及时反馈的
