### ISSUE TITLE
objc项目中无法使用，类定义请添加public

### ISSUE THREAD

**Issue by snaill** [luowenxing/MTImagePicker#3]
@objc public protocol MTImagePickerControllerDelegate:NSObjectProtocol {
    optional func imagePickerController(picker:MTImagePickerController, didFinishPickingWithModels models:[MTImagePickerModel])
    optional func imagePickerControllerDidCancel(picker: MTImagePickerController)
}

public class MTImagePickerController :UIViewController,UICollectionViewDataSource,UICollectionViewDelegate {

**Comment by snaill** [comment]
需要暴露的都要加哦

**Comment by luowenxing** [comment]
已添加。示例代码

```
    NSNumber *video = [[NSNumber alloc] initWithInt:MTImagePickerMediaTypeVideo];
    NSNumber *photo = [[NSNumber alloc] initWithInt:MTImagePickerMediaTypePhoto];
    NSArray *typeArray = [[NSArray alloc] initWithObjects:video,photo,nil];
    MTImagePickerController *vc = [MTImagePickerController instance];
    vc.delegate = self;
    vc.mediaTypesNSArray = typeArray;
    UINavigationController *nc = [[UINavigationController alloc] initWithRootViewController:vc];
    [self presentViewController:nc animated:YES completion:NULL];
```
