### ISSUE TITLE
Cannot implement it into project

### ISSUE THREAD

**Issue by felicialiying** [luowenxing/MTImagePicker#4]
I'm a beginner to swift 3 and cocoapods and i want to implement this https://github.com/luowenxing/MTImagePicker image picker for my project.

I've installed the pod into my project and am using the .xcworkspace file.

However, I'm facing problems as i've errors like:

No such module 'MTImagePicker'
Use of unresolved identifier 'MTImagePickerController'
Use of undeclared type 'MTImagePickerAssetsModel'
I've moved the MTImagePicker folder into my project as instructed.

But I'm still having this problem.

Any help is much appreciated.

Thank you so much!

**Comment by luowenxing** [comment]
The project is written in swift2.3 Syntax and has not been updated for swift3.0.
I will update for swift3.0 soon.

**Comment by luowenxing** [comment]
Update for swift3.0
