### ISSUE TITLE
通过cocoapods加载后，使用有问题

### ISSUE THREAD

**Issue by hairoi** [luowenxing/MTImagePicker#9]
有实际测试过其他项目通过cocoapods加载使用么？
我使用时发现很多方法都是没有公开，比如：
`MTImagePickerController.instance`
经查源码中写的是：
`class var instance:MTImagePickerController {
        ……
  }`
在swift项目中由于会被打包成framework，应该需要在class前面加上public才能在外部进行调用？
麻烦看一下，谢谢！

**Comment by luowenxing** [comment]
我用swift测试过cocoapods加载，oc可能确实需要加一个public

**Comment by hairoi** [comment]
我是用swift 4的项目+cocoapods 1.4.0来试的，不知道您这边使用的是不是这个版本，我按照说明文档引入之后发现两个问题，一个是前面说的源码中没有加public导致外部调用不了，另一个是作为资源文件的storyboard默认引用不到，如果您有空的话可以试试看有没有同样的问题，谢谢了

**Comment by luowenxing** [comment]
@hairoi 已经修复，亲测可以用pod安装使用
